export const GET_MANY_REQUEST = 'GET_MANY_REQUEST';
export const GET_MANY_SUCCESS = 'GET_MANY_SUCCESS';
export const GET_MANY_FAIL = 'GET_MANY_FAIL';

export const GET_ONE_REQUEST = 'GET_ONE_REQUEST';
export const GET_ONE_SUCCESS = 'GET_ONE_SUCCESS';
export const GET_ONE_FAIL = 'GET_ONE_FAIL';

export const CREATE_ONE_REQUEST = 'CREATE_ONE_REQUEST';
export const CREATE_ONE_SUCCESS = 'CREATE_ONE_SUCCESS';
export const CREATE_ONE_FAIL = 'CREATE_ONE_FAIL';

export const UPDATE_ONE_REQUEST = 'UPDATE_ONE_REQUEST';
export const UPDATE_ONE_SUCCESS = 'UPDATE_ONE_SUCCESS';
export const UPDATE_ONE_FAIL = 'UPDATE_ONE_FAIL';
export const UPDATE_ONE_RESET = 'UPDATE_ONE_RESET';

export const DELETE_ONE_REQUEST = 'DELETE_ONE_REQUEST';
export const DELETE_ONE_SUCCESS = 'DELETE_ONE_SUCCESS';
export const DELETE_ONE_FAIL = 'DELETE_ONE_FAIL';
export const DELETE_ONE_RESET = 'DELETE_ONE_RESET';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
