export const PLACE_ORDER_REQUEST = 'PLACE_ORDER_REQUEST';
export const PLACE_ORDER_SUCCESS = 'PLACE_ORDER_SUCCESS';
export const PLACE_ORDER_FAIL = 'PLACE_ORDER_FAIL';

export const GET_MY_ORDERS_REQUEST = 'GET_MY_ORDERS_REQUEST';
export const GET_MY_ORDERS_SUCCESS = 'GET_MY_ORDERS_SUCCESS';
export const GET_MY_ORDERS_FAIL = 'GET_MY_ORDERS_FAIL';

export const GET_SINGLE_ORDER_REQUEST = 'GET_SINGLE_ORDER_REQUEST';
export const GET_SINGLE_ORDER_SUCCESS = 'GET_SINGLE_ORDER_SUCCESS';
export const GET_SINGLE_ORDER_FAIL = 'GET_SINGLE_ORDER_FAIL';
