export const GET_PIZZAS_REQUEST = 'GET_PIZZAS_REQUEST';
export const GET_PIZZAS_SUCCESS = 'GET_PIZZAS_SUCCESS';
export const GET_PIZZAS_FAIL = 'GET_PIZZAS_FAIL';

export const NEW_PIZZA_REQUEST = 'NEW_PIZZA_REQUEST';
export const NEW_PIZZA_SUCCESS = 'NEW_PIZZA_SUCCESS';
export const NEW_PIZZA_FAIL = 'NEW_PIZZA_FAIL';
