export const GET_PIZZAS_REQUEST = 'GET_PIZZAS_REQUEST';
export const GET_PIZZAS_SUCCESS = 'GET_PIZZAS_SUCCESS';
export const GET_PIZZAS_FAIL = 'GET_PIZZAS_FAIL';

export const GET_PIZZA_DETAILS_REQUEST = 'GET_PIZZA_DETAILS_REQUEST';
export const GET_PIZZA_DETAILS_SUCCESS = 'GET_PIZZA_DETAILS_SUCCESS';
export const GET_PIZZA_DETAILS_FAIL = 'GET_PIZZA_DETAILS_FAIL';

export const NEW_PIZZA_REQUEST = 'NEW_PIZZA_REQUEST';
export const NEW_PIZZA_SUCCESS = 'NEW_PIZZA_SUCCESS';
export const NEW_PIZZA_FAIL = 'NEW_PIZZA_FAIL';

export const DELETE_PIZZA_REQUEST = 'DELETE_PIZZA_REQUEST';
export const DELETE_PIZZA_SUCCESS = 'DELETE_PIZZA_SUCCESS';
export const DELETE_PIZZA_RESET = 'DELETE_PIZZA_RESET';
export const DELETE_PIZZA_FAIL = 'DELETE_PIZZA_FAIL';

export const UPDATE_PIZZA_REQUEST = 'UPDATE_PIZZA_REQUEST';
export const UPDATE_PIZZA_SUCCESS = 'UPDATE_PIZZA_SUCCESS';
export const UPDATE_PIZZA_RESET = 'UPDATE_PIZZA_RESET';
export const UPDATE_PIZZA_FAIL = 'UPDATE_PIZZA_FAIL';

export const PIZZA_RESET = 'PIZZA_RESET';
